### ISSUE TITLE
Finish the ReadMe

### ISSUE THREAD

**Issue by ftslyter** [honj/INFX-551-Spring2017#1]
We need to add the last section (Data Curation). Also, add more to the rest of the file.

**Comment by ghost** [comment]
Just added some stuff under "Potential Curation Activities" and messed with formatting a bit.
Does this need anything else? Thanks!
Ben

**Comment by honj** [comment]
I think Curation Activities looks great. I can add to section 1 (Topic) tomorrow.

**Comment by ftslyter** [comment]
Normalization. YES! Something I know how to do and have experience in!

**Comment by honj** [comment]
Okay, I updated the Topic section. Let me know what you think.

**Comment by ftslyter** [comment]
I like it. Are there any other terms that we may need to clarify later on? If so, I was thinking we could start a wiki on here and put any further vocabulary into it. Again, I'm not sure if it's needed or not. Just trying to wrap my mind around this software really.

Anyhoo, thanks for updating the section.

**Comment by ghost** [comment]
Julia the topic section looks great--thank you. It is great that you defined some terms there. I didn't realize how much it needed until you made your changes.
By the by, I'm interested in our working definition of local. I'm wondering if, as we look more into this issue, we may want to refine or further limit it (400 miles is a long way!). As one example of a definition, the farmers' market in Missouri that I used to work for would only allow vendors that grew their product in the county the market was in or an adjacent county.
Frederick I think that the terms wiki is also a good idea!
Thanks everyone!
Ben

**Comment by nniiicc** [comment]
Great discussion here - just to reiterate - the readme.md can keep evolving as you go. Its good to update as you make decisions, and then record what changed in the commit message.

**Comment by ghost** [comment]
Thank you Nic; thank you team!
I like the idea of updating this as we go.
Nevertheless, for the sake of clutter-clearing, I'm going to go ahead and close this issue now that we've got our initial draft completed.

**Comment by nniiicc** [comment]
You're doing it right! 🔥
