### ISSUE TITLE
Do live CKAN demo

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#11]

**Comment by ghost** [comment]
I've put a couple of our datasets up on CKAN. The URL for my user page (to view datasets) is as follows:

http://demo.ckan.org/user/foodies_infx

(Log in info is in our GDrive folder if anybody else wants to try posting more sets.)

So far I've learned:

- Sets can be posted direct from GitHub (Click on dataset, right-click Download > Copy link address)
- Preview functionality differs based on file type (no preview for .xlsx files, preview for .csv files)
- The CSV file I posted doesn't look like anything that makes sense in the CKAN preview. What needs to happen to the file to make the preview useful?

**Comment by honj** [comment]
Cool! The WA_urban Harvest Count preview looked good to me. The CSA directory was hard to decipher, it kind of looked like there are "too many" variable names for CKAN's preview so they started wrapping around into multiple rows of headers...

**Comment by ghost** [comment]
Yeah, that's what I thought maybe happened too.

**Comment by ghost** [comment]
As there are no further specific goals for the CKAN demo at this time, I'm going to close this issue.
