### ISSUE TITLE
Review CKAN documentation

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#12]

**Comment by ftslyter** [comment]
Was there something specific we needed to do for this? I can take it on, but I just can't remember if this was an overarching review or something more specific?

**Comment by ghost** [comment]
Yes, @ftslyter  this seems like kind of an ill-defined task until we have a specific question that we need to answer...

**Comment by honj** [comment]
I think what we are looking for is possible compatibility issues or other things that could limit/influence decisions we make in other parts of the project.
For now we could just use this issue as a place to add "does CKAN work with this?" questions as they arise. Does that sound good?

**Comment by ftslyter** [comment]
do we have a section that discusses why CKAN works for our respository? perhaps that's this section.

**Comment by ghost** [comment]
That is definitely this (overall) section, project roadmap column 3, Repository - CKAN.

**Comment by ftslyter** [comment]
If that's what this overall section is for, then what is this specific section for? 

I'm going to table this one for later and focus on the others. I'll come back to it at the end of my to-do list.

**Comment by ghost** [comment]
Only remaining task/issue in this column is preparation and final review of deliverable component.
