### ISSUE TITLE
Create examples of DCAT use

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#16]

**Comment by ftslyter** [comment]
Is this the little tables with descriptions and examples we talked about?

**Comment by honj** [comment]
Yes!

**Comment by ftslyter** [comment]
So I've copied and reformated (may not look like it, but I guess that's the point) the DCAT page into this document: [Exampls of DCAT use.docx](https://github.com/honj/INFX-551-Spring2017/files/1012501/Exampls.of.DCAT.use.docx) I just wanted to make sure this format works before I go through and add a row at the bottom of each table that says Example: | blahexampleblah.

**Comment by ghost** [comment]
@ftslyter I will look at this tonight and get some feedback to you.

**Comment by ghost** [comment]
@ftslyter 

(Sorry in advance for a looooong response.)

I don't have too many comments at this point, I think that it'll help to see one of your examples. (I don't remember what exactly it was that we talked about.) 

There is one class that I don't think we need to mess with: CatalogRecord.

There are also a few classes that I don't fully understand, and so feel unsure about whether or not we need them: ConceptScheme, Concept, and Organization/Person.

Anyway, do you wanna create one or two of the examples you have in mind to go with these (just the properties, or the properties and classes?) and then we can reconvene on this issue?

Side note: This is an area of our protocol where I (we?) feel at a loss in terms of an understanding of the mechanics, or of how this metadata would actually exist/be created/etc. Is this an area where we would explain things in a more general way as opposed to creating actual metadata? Would this be a good one to reach out to Nic about?

Thank you!

**Comment by honj** [comment]
Here's the info from the Application Profiles activity that is relevant to this task:

> For each element in your application profile you should (eventually) provide the following:
>     Namespace, and namespace definition
>     Status: Mandatory or optional
>     Permitted encoding scheme for values
>     Any rules for content
>     An example
> You should also choose an encoding scheme for your examples (JSON or XML for our sake).

And here are some examples of this sort of thing in the Project Open Data schema: (https://project-open-data.cio.gov/v1.1/schema/#context)
For some reason I can't find the analogous thing in DCAT but it is probably out there.

I agree that this would be good to bring up in our meeting (or in the future). I don't think we necessarily need to create metadata records, and the examples should also show what the encoding would look like in practice - with values from our datasets/catalog.

**Comment by ftslyter** [comment]
thanks for the input, I'll get something together soonish.

**Comment by ftslyter** [comment]
For your consideration:
[Examples of DCAT use2.docx](https://github.com/honj/INFX-551-Spring2017/files/1030861/Examples.of.DCAT.use2.docx)

**Comment by ghost** [comment]
Examples doc is looking great Frederick--thank you!

**Comment by honj** [comment]
Hey, this looks super!

I like the specificity of the options for the spatial coverage - this is
really excellent. I wonder if we should also allow street addresses? I ask
only because this seems to be a very common way of expressing location in
the datasets we currently have.

**Comment by ftslyter** [comment]
Based on the criteria we have now, which we "liberally borrowed" from Project Open Data, we absolutely go down to the city-level and the GPS-type data would be the equivalent of street-level data, but I'm not sure we have the resources to convert street addresses into latitude and longitude. We could mention this somewhere in our dialogue as a possible plugin later.
