### ISSUE TITLE
Ingest, transformation, licensing and preservation policies (activity write-up)

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#19]

**Comment by honj** [comment]
Since this is a multi-part task (and I feel like I am under-assigned) let's split it up!

**Comment by ftslyter** [comment]
I'll take the first six and you take the second six? I'm sure Ben won't feel left out after he looks over our rough drafts and adds his input.

**Comment by honj** [comment]
Frederick - realized I never responded to this - sorry! That sounds great to me. Am I imagining things or did you say somewhere that you created a Google Doc to start drafting this? If not, I can make one.

**Comment by ftslyter** [comment]
I had not, but I've just created said file.

**Comment by honj** [comment]
Hi - did you share the doc? Sometimes my shared docs go missing... not sure why. Anyway, could you resend or link it? Thanks!

**Comment by ftslyter** [comment]
https://docs.google.com/a/uw.edu/document/d/1akMR1axIDbNv56vzDsg2g-BvmZ043lCEoExyDTyVNog/edit?usp=sharing

**Comment by ftslyter** [comment]
Rough draft is up! We just need to finalize and post to GitHub.

**Comment by ghost** [comment]
Will proof tonight! Thanks you two!

**Comment by honj** [comment]
Great! My section is rough but I'll clean up once you guys have a chance to
provide feedback.

**Comment by ghost** [comment]
It's looking good to me. I made a few comments in the Google Doc just now. Thank you!
UPDATE: I made my changes in the GitHub wiki page. No need to refer back to the Google Doc for my feedback. Thanks again~
