### ISSUE TITLE
Activity write up: Repository analysis

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#2]
Hi all: 
I've posted a rough draft of the activity write-up for our group discussion last Thursday and ongoing evaluation of Dataverse and CKAN repository software.
Would you guys be willing to take a look at it and let me know if I left anything important out or mixed anything up, or if you have any other comments in general?
I'll finalize this by Thursday class time. 
Thanks!
Ben

**Comment by honj** [comment]
Hi Ben! Maybe I'm being obtuse, but where is the draft posted?

**Comment by ghost** [comment]
Hi Julia! It is a new wiki page. Sorry--totally forgot to mention that.

**Comment by honj** [comment]
I just found it! Staring me in the face. I think it looks good. I added one sentence to the end of "Decision."

**Comment by ftslyter** [comment]
I thought the intro and decision were accurate and honest. I feel like that's the best we can do for now with our lack of experience in this.

**Comment by ghost** [comment]
Thanks for the feedback y'all!
Ben
