### ISSUE TITLE
(What kind of) Deliverable(?)

### ISSUE THREAD

**Issue by ftslyter** [honj/INFX-551-Spring2017#20]
What sort of deliverable are we aiming for?

GitBook was one option briefly discusses.

**Comment by ghost** [comment]
I created a GitBook account. I then tried to integrate it with my GitHub account. Because if GitBook can bring the stuff that we have already written over into our deliverable, that's great right? 
But I couldn't integrate GitBook with this repository because I'm not the owner. So, I guess in order to further explore whether this could be a good option for us, we may need @honj to make an account and then see how the integration works?

**Comment by honj** [comment]
Thanks for getting this rolling. I made a GitBook account, integrated our repository, and added Ben as a collaborator (Frederick, once you sign up on Gitbook I can add you too).
I haven't explored too deeply but it looks as if Gitbook takes the files (in markdown) that we have in our repository and assembles them in a more book-like format.

**Comment by ftslyter** [comment]
username = ftslyter

**Comment by honj** [comment]
Hi guys. It looks like you are both in the Gitbook. I just gave you both Owner permission so you should now have all the power that I do!

**Comment by honj** [comment]
Okay, I spent some time playing with Gitbook today. It looks like a nice format for presenting our work, but I'm not sure what advantages it offers beyond that. As far as I can tell, we need to create the "chapters" of the book from scratch - I am not sure what functionality syncing it with our repository offers. It did a nice automatic import of the readme.md file, but I can only figure out how to access, not import, other files.
I am still fine with using Gitbook for our deliverable but I feel like there is some functionality I am missing? Please let me know if you discover anything useful. If not, I'll ask Nic about this tomorrow.

**Comment by ghost** [comment]
Yeah, I'm not actually totally sure what the advantages would be either. Especially since I feel like we are headed towards a more text-centric overview-type deliverable, as opposed to a here's-a-repository-that-we-made-type deliverable. Might be good to ask.

**Comment by nniiicc** [comment]
The major advantages are:
- HTML rendering 
- In-line code or text snippets
- Presentation of data (you can easily embed tables)

That being said - yeah, honestly the biggest upside is appearance, and modifiability (e.g. If you want to change the order of something, you just change the directory structure). 

You can definitely just create a markdown document and publish the same thing on github. You could also just write a googledoc

**Comment by ftslyter** [comment]
I am still fine with any of the above options.

**Comment by honj** [comment]
I'm still fine with Gitbook. I think it looks nice and would be a good way to get better at markdown. I don't mind taking on the Gitbook wrangling. Thoughts?

**Comment by ftslyter** [comment]
After today's conversation, I'm still not opposed to Gitbook. A Google doc does sound easier though, depending on how much wrangling Gitbook would need.

**Comment by ghost** [comment]
@honj @ftslyter 
As per our convo following the final class meeting, our plan currently is:
Create document for editing and review in Google Drive (this is so we can use comments and other features familiar to us). 
Once document is ready for submission, we will either:
1) Make a GitBook from it for submission
2) Submit it some other way
