### ISSUE TITLE
Create workflow

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#21]
This was suggested as a component of our final deliverable by Nic in class.
The basic idea, as I understand it, is this:
What is the workflow between submission of a dataset or sets and publishing in our repository?
* What steps are involved?
* What decisions need to be made and who makes them?

**Comment by honj** [comment]
I think this could be useful, but should probably come as one of the last steps, once we have figured out our protocol and policies in as much detail as we can.
One challenge I have is the "who" - are we to assume we have a curation team? Or divide "roles" between us? Or is there one administrator - in this case the "who" is pretty simple, either the admin or the user.

**Comment by ftslyter** [comment]
Is this just a decision tree visual for our repository website to explain how our repository workflow goes? That sort of visual would give us some flexibility between the "who" questions.

**Comment by ghost** [comment]
@ftslyter Yes, that is what I'm thinking. 
And I'm still interested in creating this if it makes sense as we finalize things this week. I guess that I've always secretly wanted to make one of those wacky flying-spaghetti monster diagrams (although I promise that this would be much more simple!).

**Comment by ghost** [comment]
This did not end up happening.
