### ISSUE TITLE
Need to delete redundant home page on our wiki

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#22]
I'm not exactly sure how this happened, but one is just the boilerplate wiki home page, and one is the wiki home that has a bit of info about our group on it. 
I tried to erase the no-info one that is just sitting there taking up space, but I couldn't. Can you Julia? Thank you!

**Comment by honj** [comment]
Okay, after some experimentation I figured out that the entry page that you see upon going to the wiki must be called Home. If there is no Home page (i.e. if it is renamed) you just get a list of pages when you enter the wiki. I think that is why you can't delete it. Long story short, I just transferred the info from the LFS page Ben created into the Home page, and then deleted the former.

**Comment by ghost** [comment]
Thank you Julia!
