### ISSUE TITLE
Start using Hypothesis...

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#23]
...if you want.
It is a web-annotation extension for Chrome, and I like it, and I'm using it to annotate sites related to our project. If you want to use it, or look at my annotations, click on this link:
[https://hypothes.is/groups/pEZNxyWD/infx551-lfsgroup](url)

**Comment by honj** [comment]
Cool! I just got an account.

**Comment by ftslyter** [comment]
I use Zotero to keep track of sites I find. How does this compare?

**Comment by ghost** [comment]
@ftslyter 
So, they do different things. Hypothesis allows you to, basically, highlight and write notes in the margins of a webpage (or a PDF that lives online, etc.) as if it were a piece of paper. Then you can access these annotations, either by going back to the site or by looking at them on your Hypothesis profile page, from which you can navigate back to each individual URL at your pleasure. 
It does not, however, keep track of the info that you would need to generate a citation or bibliography, as Zotero does. 
Now if Hypothesis and Zotero got together and had a baby (Zotothesis? Hypotero?), THAT WOULD BE AMAZING!
Does this answer your question?

**Comment by ftslyter** [comment]
Yes, it does. Thanks. I think I'll skip it. I don't need more extensions/software in my life.
