### ISSUE TITLE
Upload datasets to GitHub

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#24]
Hello Foodies:

So, my trial run of putting datasets on GitHub seemed to work pretty well. 

I wanted to see how the versioning works, so after I uploaded the initial version of CSAdata.csv, I imported it into OpenRefine and did a bit of work on it. I then exported that dataset back out of OpenRefine and uploaded this new version to GitHub*. 

So, now, if you go to INFX-551-Spring2017/Data/CSAData.csv, and click on history, you will see both versions of the file. So, this must be what they mean when they say "version-control system."
I've just looked over our next activity, Curated Datasets, and it looks like we are going to be doing some refining of datasets. With this in mind, I'm going to upload the rest of the datasets that I have, along with URL information to keep things straight. The idea would be that each time we refine or work on a dataset, we make sure and upload it again so that we will continue to have access to all the versions. 

Does this make sense/sound okay?

*NOTE: When exporting a dataset back out of OpenRefine, the file name is altered. Thusly, before re-uploading to GitHub, it is necessary to change the file name back to the original. File names must be identical if the version history feature is to work.

*NOTE2: I'm sorry about this extremely long message, @honj and @ftslyter

**Comment by ftslyter** [comment]
Makes sense. Sounds okay.

**Comment by honj** [comment]
Just checked it out - looks good! I would just say that for future updates to datasets we should be sure to add informative comments to the commit so it is clear what (roughly) was changed and why. Like "Normalized variables x, y, z," etc.

**Comment by ghost** [comment]
Yes! Good point.

**Comment by honj** [comment]
Hi Foodies: I spent some time going through the Data folder today. I also made a Readme page for that folder that lists the sets we have and links to the URLs, mostly to try to give myself a better sense of the data we are working with.
Here are a couple of thoughts for how we could transform/merge some of these sets to make them more useful:
1) FEA datasets: These seem to all have the same rows (by county). Would it make sense to combine them into one giant dataset that houses all of the variables? 
2) Farming concrete datasets: FYI, you can get full datasets for the US if you just press "go" on the search page without entering any fields. Might make sense to include these instead/in addition to the WA sets.
3) Seattle.gov datasets: P-Patch Map and P-Patches seem to have the same csv file. P-Patch gardener turnover, registered gardener and plotholders are very small sets with each row representing a year - better to combine?

I also added some sets from Chicago open data to flesh things out.

**Comment by ftslyter** [comment]
As curators, is it up to us to combine datasets? Is this part of our Terms of Service? I thought we were accepting datasets and letting users find what they want via the metadata? I feel that, especially with our fictitiously limited resources, we wouldn't have the personnel to do much more than normalize and anonymize data before publishing it on the repository.

**Comment by ghost** [comment]
@ftslyter 
In answer to your question:
We need to describe how we'll extract, transform, and load (find, clean up or alter in some way that makes them more usable, and then post in cleaned-up form) datasets in our curation protocol deliverable.
More specifically, we need sample datasets for the purpose of working out what'll be some basic data-cleaning protocols. For example, if we get community garden data from multiple cities, we can figure out what is involved with normalizing the datasets, and then specify in our protocol what this process looks like, so that it could be repeated on such datasets in the future. 
So even though, as you state above, the LFS repository might focus on curating submitted data--not on searching for it--to work on curation protocols for the purposes of this assignment we have to go out and get some sample data ourselves.
