### ISSUE TITLE
Determine tasks for final write up

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#25]
Hi guys - First, thanks for all your progress on this. I know I have been absent but will be able to devote a chunk of time tomorrow (Saturday).

Second, at some point - within the next week? - we should probably decide who is responsible for the actual write up of each section for the final product. Part of that will be agreeing on what the sections will be.

**Comment by ghost** [comment]
Getting together during the coming week to work on this stuff and start divvying the writing sounds like a good plan Julia.
Tuesday or Thursday before class can work for me--could either of these work for you two?
See you at Nic's office at one on Monday.
Ben

**Comment by ftslyter** [comment]
We did this last night:
Project definition, scope, and audience (Week 2) - Ben
User stories that define stakeholders (Week 4) - Julia
Justification for selecting repository software (the system design) (Week 3) - Ben
Metadata needs, and proposed schema (Week 5) - Frederick
Deposit policies (who, what, size, formats, etc.) (Week 6) - Julia
Ingest, Transformation, Licensing, and Preservation Policies (Week 8) - Frederick
Curated datasets (Week 7 we will do an exercise on this, but you will continue to work on this throughout the quarter) - Ben

**Comment by honj** [comment]
My understanding was that these assignments were just for the presentation, not the deliverable.
Are we in agreement to take these sections for the deliverable too? Ben has 3 sections, so I'd be happy to pitch in on Curated Datasets to even it up.
Are there other sections that should be added? I remember we were talking about adding a workflow as well.

**Comment by ghost** [comment]
@honj @ftslyter 

Sorry in advance for the lengthy post.

As per "How To: Final Project Deliverables," essential components of the final deliverable are listed below. Following are names of the team member that was in charge of each section for the presentation.

1. Project definition, scope, and audience: Ben
2. User stories that define stakeholders: Julia
3. Justification for selecting repository software (the system design): Ben
4. Metadata needs, and proposed schema: Frederick
5. Deposit policies (who, what, size, formats, etc.): Julia
6. Ingest, Transformation, Licensing, and Preservation Policies: Frederick
7. Curated datasets: Ben

These 7 components match our 7 project columns. ~~Ergo, my suggestion is that I will create an issue within each column titled "Create/draft Google Doc." This will allow us to assign ourselves to segments, or discuss via issue posts how to assign segments.~~ 

This just in--Julia suggested that it'd be easier just to claim sections on the Google Doc itself, and I agree! So maybe we can just claim with a comment on the section heading?

All component documents ~~should be~~ are (thank you Frederick) shared, allowing all team members to comment on/add content to/etc. sections other than their own if they want/need to. 

Does this sound good?

**Comment by honj** [comment]
That sounds fine to me!

**Comment by ftslyter** [comment]
That's fine with me. Our Google doc has those same seven subheadings, plus an eighth (Reflection). Thus, it should be an easy direct correlation between the deliverable and the Project Roadmap.

**Comment by honj** [comment]
Thanks for starting the google doc, Frederick. 
Nic mentioned having a "Rationale for design" (or something like that) at the end of each section. Would it make sense to include these brief rationales in each section, plus a final reflection that has any overarching thoughts about the project?

**Comment by ghost** [comment]
Thank you @ftslyter ! I hadn't seen the Google Doc yet, but I've got it now--thanks for setting it up!
