### ISSUE TITLE
Identify file-naming protocols

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#32]

**Comment by ghost** [comment]
My idea for file-naming is:
*TopicName*(dot)*SpatialCoverage*(dot)*TemporalCoverage*
For example: 
CommunityGardens.NewYorkCity.Current6June2017

We would probably want to start lists of controlled vocabulary for topic names and place names, and decide on a format for dates. ( @ftslyter did you already identify a date format?)

**Comment by ghost** [comment]
It has already become apparent to me that a file-naming protocol would need to be more complex than that. 
For example, within Community Garden Datasets, there are sets that have location information, and others that have information about harvest counts, etc.
Additionally, might it be helpful to indicate data source in file names? For instance, to easily identify all datasets from Farming Concrete, etc.?
Note that the Data folder and new subfolder(s) are currently messy/undergoing transformations/etc.

**Comment by ftslyter** [comment]
date format: 2001-01-15

Ben, rather than going down the rabbit hole of complicated filenames (which could potentially just get longer and longer), what if we went the other direction and simply used a data/time stamp of either when the data was uploaded or when the data was published?

**Comment by ghost** [comment]
@ftslyter You certainly have a strong point about trying to come up with filename conventions being a rabbit-hole. So, I guess that the idea here is that when users search for datasets, the searches are querying metadata fields, making filenames which clearly indicate file content less crucial?

**Comment by ghost** [comment]
I took on a small sample of datasets and created a small-scale file naming prototype. This will serve as an example of how this could be handled. There will also be discussion of having a much simpler file-naming protocol and relying more on metadata for the purposes of identification of datasets that match user needs in searches, etc.
