### ISSUE TITLE
Identify normalization protocol for sample datasets

### ISSUE THREAD

**Issue by ghost** [honj/INFX-551-Spring2017#33]
My idea here is that I can identify a normalization protocol for some of our datasets. I'm thinking here about municipal data on community gardens. I'm going to grab some more datasets from cities and look into what kind of cleaning/normalization tasks could be routinized for future use.

**Comment by ghost** [comment]
@ftslyter 
Just noticed that you've covered lots of this ground in the ingest/transformation/etc. section--awesome! thank you! 
So I need to take a close look at what you've already got and see whether or not there is anything I need to add in the Curated Datasets section.

**Comment by ftslyter** [comment]
As we've discussed before, the transformation section does have specific mentions of normalization; however, it is meant to be vaguer than the exact/specific items you were working on for the Curated Datasets portion.

**Comment by ghost** [comment]
Thank you for taking care of this one @ftslyter !
