### ISSUE TITLE
Granular

### ISSUE THREAD

**Issue by ftslyter** [honj/INFX-551-Spring2017#5]
We seem to keep hitting a speedbump regarding granularity. (What an awkward word!) How granular do we want to go? How far is too far?

**Comment by ftslyter** [comment]
I may be mixing apples and oranges here (Get it?! Food?! I'm hilarious...) but I know we've talked about being fairly detailed regarding our geospatial information so that, for example, all the many farmer's markets in Seattle can be separated. At the same time, I'm wondering how detailed we need about keeping up with the provenance of the food items involved or even the details of descriptions of some of the food. For that matter, do we even need to keep track of each apple, bushel of apples, or orchard involved? 

Some of these are separate conversations perhaps, but when looking at the elements needed for our repository, there's a difference between needing one location element or several. Perhaps there's a level of flexibility to be had?

**Comment by ghost** [comment]
My take on this is: 
I see no problem with having datasets that vary in their granularity/specificity. AS LONG AS we make sure that these characteristics are expressed adequately in our metadata. Does this make sense?

**Comment by ftslyter** [comment]
structured flexibility works for me
