### ISSUE TITLE
Stakeholders

### ISSUE THREAD

**Issue by ftslyter** [honj/INFX-551-Spring2017#6]
Some of these decisions really are dependent on who our primary stakeholders are. We've mentioned multiple stakeholders in the LFS, but they can't all be equally important. Or can they? Who's on top of the list?

**Comment by ftslyter** [comment]
I think, for me, one of the issues I'm having is that I need to know who I'm catering to. My mind works in more of a straight line if I know who the end user is. We've discussed multiple echelons of humans that may be interested in this data. However, that just leaves me trying to build a repository for everyone. 

We, the curators, are hypothetically putting the information in the system (I think). So where/how are we getting this information? And then it goes through us into the repository, and who then uses it? The first group would determine what information we have and the second group would determine what information is needed.

**Comment by ghost** [comment]
Frederick, the "Users" section in the doc below should answer this question. If not, I need to rewrite it. 

[Definition.Scope.Users.docx](https://github.com/honj/INFX-551-Spring2017/files/1016446/Definition.Scope.Users.docx)
