### ISSUE TITLE
Review/refine project definition, scope, audience

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#7]

**Comment by ries07uw** [comment]
The writeup for this project component is underway and lives here:
INFX-551-Spring2017/Documentation/project definition, etc.md

**Comment by ries07uw** [comment]
The writeup for this component of our deliverable is underway, based on our original README, and lives here:
[https://github.com/honj/INFX-551-Spring2017/blob/master/Documentation/project%20definition,%20etc.md](url)

**Comment by ries07uw** [comment]
The write-up for this component of our deliverable is underway. It lives here:

INFX-551-Spring2017/Documentation/project definition, etc.md

**Comment by ghost** [comment]
A proposed write-up for this component of our project is here:

https://drive.google.com/open?id=18qhG2O8l03P5oZ6gCQB8wG45uqhOQxHAzP0qOXpxbfk

Take a look and give feedback if you've got it. I'm leaving the issue open for now.
Thanks, Ben

**Comment by ftslyter** [comment]
"page not found"

Is it the Definition.Scope.Users file in the LFS folder? If so, it looks good to me.

**Comment by ghost** [comment]
Dangit! Links are funny in these issues comments. I don't think that I've gotten one to work properly yet...
Yes, that is it.
LFS Group >Documentation > Definition.Scope.Users

**Comment by honj** [comment]
I like it! Do you envision this replacing our current Readme (Introduction) file?

**Comment by ghost** [comment]
I do, if you all are okay with that. I mean, replacing the readme here and then being the intro section to our final deliverable, whatever form that takes.

**Comment by ghost** [comment]
Review was completed in advance of presentation. The only remaining task/issue in this column is preparation of the final-deliverable component.
