### ISSUE TITLE
Review/add to user stories

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#8]
Provide coverage of more complete range of stakeholders

**Comment by honj** [comment]
Here are a couple more user stories to cover a wider range of user types. Any other users we should be considering?

### Civic hacker
As a person who likes to make apps for the social good, I want to have up-to-date data that will can users can rely on to find local food resources.
**How to satisfy?**
Data should be updated regularly, and should not have any gaps in availability so apps drawing from the data are up to date and functional.

### Policymaker
As a city planner, I want to know what is going on in other urban areas so that I can adopt best practices around local food systems from elsewhere.
**How to satisfy?**
Draw datasets from diverse areas. Include reliable contact information so that policymakers and advocates can build their networks.

**Comment by ftslyter** [comment]
I like both of these additions.
